### ISSUE TITLE
can't get app och.comp.db.base.exception.UniversalSqlException,Syntax error in SQL statement

### ISSUE THREAD

**Issue by rhsy445566** [edolganov/live-chat-engine#3]
hi
I have a problem,run this system, and the log shows that there is a error：
![20150905110617](https://cloud.githubusercontent.com/assets/5152093/9697446/83a04ba4-53c0-11e5-816b-3c0238304b0a.jpg)
![20150905112151](https://cloud.githubusercontent.com/assets/5152093/9697447/83ba1214-53c0-11e5-9c73-fb29ea30a6a9.png)
![20150905112211](https://cloud.githubusercontent.com/assets/5152093/9697448/83bc6636-53c0-11e5-8901-351fa87321d1.png)

**Comment by edolganov** [comment]
Hello, rhsy445566!
It seems that your H2 database is not created properly. So your log is only next step but not the main issue. 

Please:
- remove %userprofile%/livechat db file (livechat.mv.db)
- remove \build_servers\chat-node-server\data dir if exists
- try to run again

If the issue will continues - please copy full calalina.log of chat-front-server and logs of h2-server (copy it from console window)

**Comment by rhsy445566** [comment]
OK,Thank you very much
