### ISSUE TITLE
Use IP address can not access？

### ISSUE THREAD

**Issue by rhsy445566** [edolganov/live-chat-engine#4]
In the same LAN, such as 192.168.1.*. Only in the access to localhost, in the same network segment of the other computers can not connection database to chat.

**Comment by edolganov** [comment]
No, all servers (front, node, central, db) can be run and communicate in different urls.

Maybe you have some bad configs?
For example we have 4 different url for all servers:
192.168.1.XXX - databse
192.168.1.YYY - node
192.168.1.ZZZ - central
192.168.1.QQQ - front

Check this files:
- _servers\chat-central-server\net-props\db.properties
  **db_url=jdbc:h2:tcp://192.168.1.XXX/~/livechat**
  This is the connection url to database
- _servers\chat-central-server\net-props\front.properties
  **chats_server_init_urls=http://192.168.1.YYY:10180 https://192.168.1.YYY:10543**
  This is node-server url to store in database (table "servers")
- _servers\chat-front-server\webapps\ROOT\WEB-INF\front.properties
  **netProps_front_host=192.168.1.ZZZ**
  This is chat-central-server url for front
- _servers\chat-node-server\webapps\ROOT\WEB-INF\front.properties
  **netProps_front_host=192.168.1.ZZZ**
  This is chat-central-server url for node

If you have any stacktraces all other info please post it

**Comment by rhsy445566** [comment]
"_servers\chat-node-server\webapps\ROOT\WEB-INF\front.properties"
No "front.properties"

**Comment by rhsy445566** [comment]
If you can be a simple point, all the servers are on a web site, such as 192.168.1.102.How to configure？
Now, I visit http://192.168.1.102:10280 on the IP address for 192.168.1.104,click on "ask a question", showing "connect error"
